---
extends:
  - alloy
  - alloy/typescript
env:
  mocha: true
  jquery: true
  node: true
globals:
  expect: true
rules:
  no-invalid-this: 0
  eol-last:
    - error
    - always
  '@typescript-eslint/prefer-optional-chain': 0
  guard-for-in: 0
