stages:
  - build
  - deploy

build:
  stage: build

  image: node:12

  services:
    - mysql:5

  variables:
    # Gitlab mysql service setup
    MYSQL_DATABASE: cronpush_test
    MYSQL_ROOT_PASSWORD: password

    # Cronpush setup
    JWT_SECRET: shhhh

    MYSQL_HOST: mysql
    MYSQL_PORT: 3306
    MYSQL_USER: root
    MYSQL_PASSWORD: password
    MYSQL_TEST_DB: cronpush_test

  cache:
    key: ${CI_COMMIT_REF_SLUG}-${CI_JOB_STAGE}
    paths:
      - .npm/

  before_script:
    - npm ci --cache .npm --prefer-offline

  script:
    - npm run quality:check
    - npm run build
    - npm test

  artifacts:
    paths:
      - bin/

deploy:
  stage: deploy
  image: alpine
  only:
    - release
  before_script:
    # SSH and rsync Setup
    - apk add --update --no-cache openssh rsync

    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - rsync --rsh ssh --recursive --delete bin package.json package-lock.json cron-push@cronpush.tygr.info:cron-push
    - ssh cron-push@cronpush.tygr.info 'bash -sl' < ./deploy.sh
